spring:
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    check-template-location: true
    content-type: text/html
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/local?characterEncoding=utf-8&serverTimeZone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true

#server:
#  servlet:
#    context-path: /demo